language: python
cache: pip

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'pypy'

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew upgrade python3
    python3 --version
  fi
install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    pip3 install tox
  else
    pip install tox
  fi

script:
  - 'tox'

matrix:
  fast_finish: true
  include:
    # One-off runs
    - python: '3.7'
      env: TOXENV=coverage
    - python: '3.7'
      env: TOXENV=pylint

    # OSX -- takes a while to start up on Travis, so once we get a worker just
    # run them all with one instance of tox
    - os: osx
      language: generic
      env: TOXENV=py27,py34,py35,py36,py37

    # Windows -- only limited versions of Python available. In any case, we
    # only really care about testing Windows compatibility, so just run the
    # system one.
    - os: windows
      language: generic
      env: TOXENV=system

# This is required to enable container based Travis CI infrastructure.
# See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
